### ISSUE TITLE
Nav menu's "Begin Meet" breaks upon opening

### ISSUE THREAD

**Issue by RaneLafraze** [LawnmowerDave/Sportwatch_app#3]
When opening or closing the menu, the "Begin Meet" option has text that breaks and changes as the menu expands open or closed.

![navbug](https://user-images.githubusercontent.com/12915796/51260612-ac5e2180-197c-11e9-894e-1f8806b536b7.gif)

**Comment by BroManSalaam** [comment]
Yup, saw that, just need to make it expand further/faster or make the font
smaller, or shorten the text

**Comment by RaneLafraze** [comment]
Removed this tab, no longer relevant
