### ISSUE TITLE
Sportwatch text is visible in welcome page

### ISSUE THREAD

**Issue by RaneLafraze** [LawnmowerDave/Sportwatch_app#5]
“Sportwatch” text is visible when logging out and re-logging in within the same session. To reproduce, log out of an account and go to Welcome page.
![9F3A4E17-9BCB-4274-8404-8F288A2F6CDA](https://user-images.githubusercontent.com/12915796/58386931-ba7c1880-7fd4-11e9-93b7-9493f2205f3b.jpeg)

**Comment by BroManSalaam** [comment]
Gotcha, good work son.
